### ISSUE TITLE
Make sure the nametag appear in the bottom right corner of user foreground

### ISSUE THREAD

**Issue by Shaomei** [aimpowered/LibOrate#44]
Currently, the nametag seems to be floating:
<img width="1079" alt="Screenshot 2024-04-17 at 9 31 22 AM" src="https://github.com/aimpowered/ZoomCompanion/assets/202047/8c62ab6b-022b-4d8c-b1f8-d2f6aa33a8ba">

But per design, it should appear in the bottom right corner:
<img width="849" alt="Screenshot 2024-04-17 at 9 34 15 AM" src="https://github.com/aimpowered/ZoomCompanion/assets/202047/c9b7459c-a942-41e0-86cd-9fd862059da7">

**Comment by Shaomei** [comment]
It seems that the name tag moves when someone turn off and turn on the video again.

**Comment by Shaomei** [comment]
@kexinF Can you look into this? I think the change should happen inside function```drawEverythingToImage``` in  ```lib/draw_badge_api.ts``` file.

I actually sometimes have trouble seeing the nametag badge at all, and will only see it after turning off and turning on my video (it will appear in the middle). I suspect the original placement is outside my window size. Can you make the position and size of the nametag relative to the user's window size?

**Comment by kexinF** [comment]
Some other developers also had similar problem:
https://devforum.zoom.us/t/how-to-get-the-actual-size-of-the-video-rendered-in-canvas-because-i-found-that-the-size-specified-in-rendervideo-is-not-the-actual-rendered-width-and-height/54258/4
https://devforum.zoom.us/t/how-to-get-user-users-screen-size-to-draw-things/87912/6

I tried to detect the camera size using getmedia: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
It worked in the browser, but I don't think zoom app browser supports it.

Let's discuss other possible solutions in the meeting. @Shaomei

**Comment by Shaomei** [comment]
This is fixed by PR #90
